AsciiIdentifiers:
  Enabled: false # 日本語使えるから使わせて貰うわ

AsciiComments:
  Enabled: false # 英語版は英語のコメント添えているからいい・・・

AccessorMethodName:
  Enabled: false # Protocol method verbs are the exception

Style/MethodName:
  Enabled: false # Different method usage should be designated with different styles

Style/DefWithParentheses:
  Enabled: false # While a lot of people don't like parenthesis they can often add clarification

Metrics/MethodLength:
  Max: 17 # A ton of one-off helper methods is worse than a longer method

Metrics/ClassLength:
  Max: 199 # Splitting some mix-ins can make code harder to read - add a little leeway

Style/ClassVars:
  Enabled: false # We're using them on purpose as static containers, instance vars won't retain

Lint/UselessAccessModifier:
  Enabled: false # without private designator methods were not private... rubocop bug?

LineLength:
  Max: 99 # safe for documentation

RedundantReturn:
  Enabled: false # flow control should be clear

VariableName:
  Enabled: false # we use proper names for static globals

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'manabu.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
